### ISSUE TITLE
AVAX event processor failed with a bunch of errors

### ISSUE THREAD

**Issue by walkjivefly** [blocknetdx/XQuery#27]
Container log ends with
```
2022-04-19 14:13:56,812 INFO     54 AVAX_PANGOLIN 13608466 BACKWARD
2022-04-19 14:13:57,030 INFO     44 AVAX_PANGOLIN 13626439 FORWARD
2022-04-19 14:13:57,136 INFO     109 SUCCESS QUERY:Approval XHASH:8c674548dc835d1aafd4c52d56fbc70edf32e4d4d40dd87bd028cbeaeed151dd TX:0x519987f6594f19f73216e4ba6e53094d011541f61fdb4899ae3bb52dc2a2aa29
2022-04-19 14:13:57,147 INFO     87 SUCCESS QUERY:Withdrawal XHASH:059df7d788fb69eb611927950c4c42eb3337a79b9092ccdae1476b82c67408eb TX:0x519987f6594f19f73216e4ba6e53094d011541f61fdb4899ae3bb52dc2a2aa29
2022-04-19 14:13:57,204 INFO     97 SUCCESS QUERY:Transfer XHASH:cb88b5402d42f3cb2dbb4fb1252d5d6dfdf35af970d6ff76b2fd7c192c4727e6 TX:0x519987f6594f19f73216e4ba6e53094d011541f61fdb4899ae3bb52dc2a2aa29
2022-04-19 14:13:57,398 INFO     54 AVAX_PANGOLIN 13608465 BACKWARD
2022-04-19 14:13:57,507 INFO     44 AVAX_PANGOLIN 13626440 FORWARD
2022-04-19 14:13:57,625 INFO     54 AVAX_PANGOLIN 13608464 BACKWARD
2022-04-19 14:13:57,762 INFO     44 AVAX_PANGOLIN 13626441 FORWARD
2022-04-19 14:13:58,044 INFO     44 AVAX_PANGOLIN 13626441 FORWARD
2022-04-19 14:15:07,933 CRITICAL Exception in worker: 109
Traceback (most recent call last):
  File "/app/manager/eventhandler.py", line 394, in queue_handler
    self.event_queue.task_done()
  File "<string>", line 2, in task_done
  File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 14:15:07,913 CRITICAL Exception in Back Listener loop!
Traceback (most recent call last):
  File "/app/manager/eventhandler.py", line 291, in back_loop
    self.event_queue.put(event)
  File "<string>", line 2, in put
  File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
2022-04-19 14:15:08,078 INFO     54 AVAX_PANGOLIN 13608464 BACKWARD
2022-04-19 14:15:07,912 CRITICAL Exception in worker: 97
Traceback (most recent call last):
  File "/app/manager/eventhandler.py", line 394, in queue_handler
    self.event_queue.task_done()
  File "<string>", line 2, in task_done
  File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 14:15:07,919 CRITICAL Exception in Listener loop!
Traceback (most recent call last):
  File "/app/manager/eventhandler.py", line 260, in forward_loop
    self.event_queue.put(event)
  File "<string>", line 2, in put
  File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 14:15:08,168 INFO     44 AVAX_PANGOLIN 13626441 FORWARD
```
Container stayed up but not doing anything.

**Comment by walkjivefly** [comment]
Restarted the stack and after AVAX resynced the AVAX event processor log has a new bunch of errors:
```
2022-04-26 19:41:03,828 INFO     AVAX_PANGOLIN node syncing... Retrying in 30 seconds
2022-04-26 19:41:33,870 INFO     AVAX_PANGOLIN node is live... Resuming
2022-04-26 19:41:33,870 INFO     Starting Loop...
2022-04-26 19:41:35,762 INFO     Connecting...
2022-04-26 19:41:35,774 INFO     Initializing Connection
2022-04-26 19:41:36,802 INFO     Trying Connection
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
2022-04-26 19:50:38,587 INFO     48 Starting forward listener...
2022-04-26 19:50:38,595 INFO     48 AVAX_PANGOLIN 13936771 FORWARD
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 354, in merge_stats
    value = unpickler.load()
_pickle.UnpicklingError: pickle data was truncated
2022-04-26 19:50:38,788 INFO     52 Starting back listener...
2022-04-26 19:50:38,811 INFO     52 AVAX_PANGOLIN 13936771 BACKWARD
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 354, in merge_stats
    value = unpickler.load()
_pickle.UnpicklingError: pickle data was truncated
2022-04-26 19:50:41,174 INFO     52 AVAX_PANGOLIN 13936770 BACKWARD
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
2022-04-26 19:50:41,474 INFO     48 AVAX_PANGOLIN 13936772 FORWARD
2022-04-26 19:50:41,673 INFO     52 AVAX_PANGOLIN 13936769 BACKWARD
2022-04-26 19:50:42,051 INFO     48 AVAX_PANGOLIN 13936773 FORWARD
2022-04-26 19:50:42,132 INFO     52 AVAX_PANGOLIN 13936768 BACKWARD
2022-04-26 19:50:42,447 INFO     52 AVAX_PANGOLIN 13936767 BACKWARD
2022-04-26 19:50:42,920 INFO     52 AVAX_PANGOLIN 13936766 BACKWARD
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 357, in merge_stats
    setattr(x, n, value[i])
TypeError: 'float' object is not subscriptable
2022-04-26 19:50:43,156 INFO     52 AVAX_PANGOLIN 13936765 BACKWARD
2022-04-26 19:50:43,337 INFO     48 AVAX_PANGOLIN 13936773 FORWARD
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 354, in merge_stats
    value = unpickler.load()
EOFError: Ran out of input
2022-04-26 19:50:43,732 INFO     52 AVAX_PANGOLIN 13936764 BACKWARD
2022-04-26 19:50:43,991 INFO     52 AVAX_PANGOLIN 13936763 BACKWARD
2022-04-26 19:50:44,077 INFO     48 AVAX_PANGOLIN 13936774 FORWARD
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 354, in merge_stats
    value = unpickler.load()
_pickle.UnpicklingError: pickle data was truncated
2022-04-26 19:50:44,925 INFO     52 AVAX_PANGOLIN 13936762 BACKWARD
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_sigqueue.py", line 41, in run
    self.process(*item)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 797, in cpu_sigqueue_processor
    Scalene.output_profile()
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 734, in output_profile
    did_output: bool = output.output_profiles(
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_output.py", line 327, in output_profiles
    stats.merge_stats(python_alias_dir)
  File "/usr/local/lib/python3.9/site-packages/scalene/scalene_statistics.py", line 354, in merge_stats
    value = unpickler.load()
_pickle.UnpicklingError: pickle data was truncated
2022-04-26 19:50:45,465 INFO     48 AVAX_PANGOLIN 13936774 FORWARD
```
but the chain is being processed:
```
2022-04-26 20:34:17,146 INFO     52 AVAX_PANGOLIN 13932396 BACKWARD
2022-04-26 20:34:17,255 INFO     52 AVAX_PANGOLIN 13932395 BACKWARD
2022-04-26 20:34:17,534 INFO     52 AVAX_PANGOLIN 13932394 BACKWARD
2022-04-26 20:34:17,718 INFO     52 AVAX_PANGOLIN 13932393 BACKWARD
2022-04-26 20:34:18,074 INFO     52 AVAX_PANGOLIN 13932392 BACKWARD
```
